# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('comments_engine', models.TextField(blank=True)),
                ('comments_points', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'champs',
                'managed': False,
            },
        ),
    ]
